# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  
lane :screenshots do
    snapshot(scheme: "fastlanepoc")
   end
lane :test do
    scan(scheme: “fastlanepoc”)
   end

lane :beta do
  
end


lane :build do
xcodebuild(
  archive: true,
  archive_path: "./build/MyApp.xcarchive",
  scheme: “fastlanepoc”,
  build: true,
  build_settings: {
      "CODE_SIGNING_REQUIRED" => "NO",
      "CODE_SIGN_IDENTITY" => ""
    } 
)

 end

end
